### ISSUE TITLE
NO IOCs DOWNLOADED

### ISSUE THREAD

**Issue by gitQuestions** [xme/toolbox#5]
Hi there,

Im using the script to download some IOCs from my MISP in order to import them to OSSEC.

I have been using "print()" to see where the script stops wornking and I realize that it is just before:
![image](https://user-images.githubusercontent.com/37657672/37775671-d28df66c-2de3-11e8-95ca-1c9520e10942.png)

I have executed the script with the commando line:
![image](https://user-images.githubusercontent.com/37657672/37775768-154bf80a-2de4-11e8-8144-ebe3b05ff281.png)

The output file is:
![image](https://user-images.githubusercontent.com/37657672/37775812-31d7bd10-2de4-11e8-8d94-3fe0d7a5adc3.png)

I hope someone HELP ME!, ANY SUGGESTION??

Thanks.

**Comment by xme** [comment]
Did you configure your environment with the correct MISP URL & key?

**Comment by gitQuestions** [comment]
Yes, the MISP URL and the key are correct.

 When I use other key or URL, a connection problem happens (dont create the file "misp_windows_ioc.txt"). So, that is not the problem.

Thanks for the answer!

**Comment by gitQuestions** [comment]
I have noticed that if I introduce "print(result['response'])", the output is just "[]".

I have tried with the file "last.py" which it writes in a output file the X last entries and the result is the same.
What "last.py" makes:
![image](https://user-images.githubusercontent.com/37657672/37821256-6d689e04-2e83-11e8-8daf-ea0fd6f1e3f1.png)

The output: just "[]"
![image](https://user-images.githubusercontent.com/37657672/37821365-a8a9e43c-2e83-11e8-9fbb-34f2322f9d6f.png)

**Comment by xme** [comment]
Can you manually the connection to MISP (via wget or curl) from the host running mof.py.

**Comment by gitQuestions** [comment]
I tried it and I got the events information:
![image](https://user-images.githubusercontent.com/37657672/37828131-5c6637c6-2e9a-11e8-8066-7bb86e3763a7.png)

Here, a link with another thread about my problem: "https://github.com/MISP/PyMISP/issues/208".

In summary, I think the problem is in the function "search()". I have try the script "get.py" (function "get_event()") and I got the information...

**Comment by gitQuestions** [comment]
FINALLY WORKS!!!!!!! The final problem was me and my lack of knowledge about MISP.

# Thank you for the support and advices.

Great community and owners.
